language: php

php:
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS="--prefer-stable"
    - COMPOSER_MODE="install"
    - COMPOSER_MODE="update"

install:
  - composer self-update
  - composer $COMPOSER_MODE --no-interaction --prefer-source $COMPOSER_FLAGS

script:
  - vendor/bin/codecept run
